### ISSUE TITLE
[ERROR] Failed to fetch the track, may be a paid resource. [INFO] Fetch track 153/1250 ... 

### ISSUE THREAD

**Issue by ndcc5** [smallmuou/xmlyfetcher#19]
[ERROR] Failed to fetch the track, may be a paid resource.
[INFO] Fetch track 153/1250 ...
[ERROR] Failed to fetch the track, may be a paid resource.
[INFO] Fetch track 154/1250 ...
[ERROR] Failed to fetch the track, may be a paid resource.
[INFO] Fetch track 155/1250 ...

**Comment by WhiteFu** [comment]
The same question

**Comment by WhiteFu** [comment]
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'reload' is not defined
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'reload' is not defined
[ERROR] Failed to fetch the track, may be a paid resource.

How to solve it ?

**Comment by samulo7** [comment]
> The same question

付费自愿无法下载
